apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/zookeeper"
