apiVersion: v1
kind: Service
metadata: 
  name: nifisn02-service
spec:
  selector:
      app: nifisn
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30200 
