apiVersion: v1
kind: Service
metadata: 
  name: nifit1-ss
spec:
  selector:
      app: nifiss
  type: NodePort
  ports:
    - name: "6980"
      protocol: TCP
      port: 6980
      targetPort: 8080
      nodePort: 30000     
