apiVersion: v1
kind: Service
metadata: 
  name: nifit2-ss
spec:
  selector:
      app: nifiss
  type: NodePort
  ports:
    - protocol: TCP
      port: 6979
      targetPort: 8080
      nodePort: 30001     
